#!/bin/bash
interpreterPath="$(which python3)"
pip3 install virtualenv
virtualenv -p $interpreterPath venv
source venv/bin/activate
pip3 install -r requirements.txt
echo "To exit this environment, please type this command 'deactivate'"